SELECT A.CART_ID
FROM (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Yogurt') AS A,
     (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Milk') AS B
WHERE A.CART_ID = B.CART_ID

--ORACLE SQL
SELECT A.CART_ID
FROM CART_PRODUCTS A, CART_PRODUCTS B
WHERE A.CART_ID=B.CART_ID AND A.NAME='Milk' AND B.NAME='Yogurt';

SELECT A.CART_ID
FROM CART_PRODUCTS A JOIN CART_PRODUCTS B
ON A.CART_ID=B.CART_ID
WHERE A.NAME='Milk' AND B.NAME='Yogurt';
