SELECT HOUR(DATETIME) AS 'HOUR', COUNT(*) AS 'COUNT'
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) BETWEEN 9 AND 20
GROUP BY HOUR
ORDER BY HOUR;

-- BETWEEN, HOUR, GROUP BY 사용하여 해결
-- https://programmers.co.kr/learn/courses/30/lessons/59412