SELECT ANIMAL_INS.ANIMAL_ID,ANIMAL_INS.NAME
FROM ANIMAL_INS,ANIMAL_OUTS
WHERE ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID AND ANIMAL_INS.DATETIME > ANIMAL_OUTS.DATETIME
ORDER BY ANIMAL_INS.DATETIME ASC;


-- oracle
SELECT ANIMAL_INS.ANIMAL_ID,ANIMAL_INS.NAME
FROM ANIMAL_INS,ANIMAL_OUTS
WHERE ANIMAL_OUTS.DATETIME<ANIMAL_INS.DATETIME and ANIMAL_OUTS.ANIMAL_ID=ANIMAL_INS.ANIMAL_ID
ORDER BY ANIMAL_INS.DATETIME asc;

SELECT i.ANIMAL_ID,i.NAME
FROM ANIMAL_INS i,ANIMAL_OUTS o
WHERE o.DATETIME<i.DATETIME and o.ANIMAL_ID=i.ANIMAL_ID
ORDER BY i.DATETIME asc;
